name: 'fÎ²3: ğŸ§¹ğŸ§¼ğŸ§¹ æƒé™¤'

on:
  workflow_dispatch:
    inputs:
      minutes:
        required: false
        description: 'åˆ†'
        type: number
      seconds:
        required: false
        description: 'ç§’'
        type: number
      note:
        required: false
        description: 'ãƒ¡ãƒ¢'
        type: string
      areas1:
        required: true
        description: 'ã‚¨ãƒªã‚¢ 1'
        type: choice
        options:
          - ''
          - 'ãƒªãƒ“ãƒ³ã‚°'
          - 'å»Šä¸‹'
          - 'ç„é–¢'
          - 'æ´—é¢æ‰€'
          - 'ã‚­ãƒƒãƒãƒ³'
          - 'ã‚·ãƒ£ãƒ¯ãƒ¼ãƒ«ãƒ¼ãƒ '
          - 'ãƒˆã‚¤ãƒ¬'
      areas2:
        required: false
        description: 'ã‚¨ãƒªã‚¢ 2'
        type: choice
        options:
          - ''
          - 'ãƒªãƒ“ãƒ³ã‚°'
          - 'å»Šä¸‹'
          - 'ç„é–¢'
          - 'æ´—é¢æ‰€'
          - 'ã‚­ãƒƒãƒãƒ³'
          - 'ã‚·ãƒ£ãƒ¯ãƒ¼ãƒ«ãƒ¼ãƒ '
          - 'ãƒˆã‚¤ãƒ¬'
      areas3:
        required: false
        description: 'ã‚¨ãƒªã‚¢ 3'
        type: choice
        options:
          - ''
          - 'ãƒªãƒ“ãƒ³ã‚°'
          - 'å»Šä¸‹'
          - 'ç„é–¢'
          - 'æ´—é¢æ‰€'
          - 'ã‚­ãƒƒãƒãƒ³'
          - 'ã‚·ãƒ£ãƒ¯ãƒ¼ãƒ«ãƒ¼ãƒ '
          - 'ãƒˆã‚¤ãƒ¬'
      areas4:
        required: false
        description: 'ã‚¨ãƒªã‚¢ 4'
        type: choice
        options:
          - ''
          - 'ãƒªãƒ“ãƒ³ã‚°'
          - 'å»Šä¸‹'
          - 'ç„é–¢'
          - 'æ´—é¢æ‰€'
          - 'ã‚­ãƒƒãƒãƒ³'
          - 'ã‚·ãƒ£ãƒ¯ãƒ¼ãƒ«ãƒ¼ãƒ '
          - 'ãƒˆã‚¤ãƒ¬'
      areas5:
        required: false
        description: 'ã‚¨ãƒªã‚¢ 5'
        type: string
      areas6:
        required: false
        description: 'ã‚¨ãƒªã‚¢ 6'
        type: string
      areas7:
        required: false
        description: 'ã‚¨ãƒªã‚¢ 7'
        type: string

jobs:
  cleaning:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "housework å®¶äº‹"
      template_name: "cleaning"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
