name: 'bÎ¶Ğ°: ğŸ“ğŸ“ ã‚¯ãƒªãƒƒãƒ”ãƒ³ã‚°'

on:
  workflow_dispatch:
    inputs:
      site1:
        required: true
        description: 'ã‚µã‚¤ãƒˆ 1ï¼ˆãƒªãƒ³ã‚¯ä»˜ãï¼‰'
        type: string
      category:
        required: true
        description: 'ã‚¿ã‚°'
        type: choice
        options:
          - ''
          - 'YouTube'
          - 'dotinstall'
          - 'ChatGPT'
          - 'æŠ€è¡“è¨˜äº‹'
          - 'ãƒ‘ãƒ¬ã‚ªãªç”·'
          - 'D ãƒ©ãƒœ'
          - 'Amazon Prime'
          - 'Netflix'
          - 'AbemaTV'
          - 'ãƒ‹ã‚³ãƒ‹ã‚³å‹•ç”»'
          - 'ãƒ–ãƒ­ã‚°'
          - 'ã‚¦ã‚§ãƒ–è¨˜äº‹'
      impression:
        required: false
        description: 'æ„Ÿæƒ³'
        type: string
      progress:
        required: false
        description: 'é€²æ—ç‡ï¼ˆå‹•ç”»ã®ä¾‹: "12:34"ï¼‰'
        type: string
      site2:
        required: false
        description: 'ã‚µã‚¤ãƒˆ 2ï¼ˆãƒªãƒ³ã‚¯ä»˜ãï¼‰'
        type: string
      site3:
        required: false
        description: 'ã‚µã‚¤ãƒˆ 3ï¼ˆãƒªãƒ³ã‚¯ä»˜ãï¼‰'
        type: string
      site4:
        required: false
        description: 'ã‚µã‚¤ãƒˆ 4ï¼ˆãƒªãƒ³ã‚¯ä»˜ãï¼‰'
        type: string
      site5:
        required: false
        description: 'ã‚µã‚¤ãƒˆ 5ï¼ˆãƒªãƒ³ã‚¯ä»˜ãï¼‰'
        type: string
      site6:
        required: false
        description: 'ã‚µã‚¤ãƒˆ 6ï¼ˆãƒªãƒ³ã‚¯ä»˜ãï¼‰'
        type: string
      site7:
        required: false
        description: 'ã‚µã‚¤ãƒˆ 7ï¼ˆãƒªãƒ³ã‚¯ä»˜ãï¼‰'
        type: string

jobs:
  clippings:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "clippings ã‚¯ãƒªãƒƒãƒ”ãƒ³ã‚°"
      template_name: "clippings"
      template_repo: "noraworld/diary-templates"
      version: "0.2.3"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
