name: '09-1: ğŸ“ğŸ“ ã‚¯ãƒªãƒƒãƒ”ãƒ³ã‚°'

on:
  workflow_dispatch:
    inputs:
      site:
        required: true
        description: 'ã‚µã‚¤ãƒˆï¼ˆãƒªãƒ³ã‚¯ä»˜ãï¼‰'
        type: string
      type:
        required: true
        description: 'ã‚¿ã‚°'
        type: choice
        options:
          - ''
          - 'YouTube'
          - 'ãƒ‹ã‚³ãƒ‹ã‚³å‹•ç”»'
          - 'AbemaTV'
          - 'Netflix'
          - 'Amazon Prime'
          - ''
          - 'dotinstall'
          - 'D ãƒ©ãƒœ'
          - 'ãƒ‘ãƒ¬ã‚ªãªç”·'
          - ''
          - 'ãƒ–ãƒ­ã‚°'
          - 'ã‚¦ã‚§ãƒ–è¨˜äº‹'
          - 'æŠ€è¡“è¨˜äº‹'
      progress:
        required: false
        description: 'é€²æ—ç‡ï¼ˆå‹•ç”»ã®ä¾‹: "12:34"ï¼‰'
        type: string
      impression:
        required: false
        description: 'æ„Ÿæƒ³'
        type: string

jobs:
  clippings:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "clippings ã‚¯ãƒªãƒƒãƒ”ãƒ³ã‚°"
      template_name: "clippings"
      template_repo: "noraworld/diary-templates"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
