name: 'fÎ²1: ğŸ§¹ğŸ§¼ğŸ§½ é£Ÿå™¨æ´—ã„'

on:
  workflow_dispatch:
    inputs:
      dishes1:
        required: true
        description: 'é£Ÿå™¨ 1'
        type: choice
        options:
          - ''
          - 'ãƒ—ãƒ­ãƒ†ã‚¤ãƒ³ã‚¹ãƒ—ãƒ¼ãƒ³'
          - 'ãƒ—ãƒ­ãƒ†ã‚¤ãƒ³ã‚·ã‚§ã‚¤ã‚«ãƒ¼'
          - 'ã‚³ãƒ¼ãƒ’ãƒ¼ã‚«ãƒƒãƒ—'
          - 'ã‚¹ãƒ—ãƒ¼ãƒ³'
          - 'ã©ã‚“ã¶ã‚Š'
      dishes2:
        required: false
        description: 'é£Ÿå™¨ 2'
        type: choice
        options:
          - ''
          - 'ãƒ—ãƒ­ãƒ†ã‚¤ãƒ³ã‚¹ãƒ—ãƒ¼ãƒ³'
          - 'ãƒ—ãƒ­ãƒ†ã‚¤ãƒ³ã‚·ã‚§ã‚¤ã‚«ãƒ¼'
          - 'ã‚³ãƒ¼ãƒ’ãƒ¼ã‚«ãƒƒãƒ—'
          - 'ã‚¹ãƒ—ãƒ¼ãƒ³'
          - 'ã©ã‚“ã¶ã‚Š'
      dishes3:
        required: false
        description: 'é£Ÿå™¨ 3'
        type: choice
        options:
          - ''
          - 'ãƒ—ãƒ­ãƒ†ã‚¤ãƒ³ã‚¹ãƒ—ãƒ¼ãƒ³'
          - 'ãƒ—ãƒ­ãƒ†ã‚¤ãƒ³ã‚·ã‚§ã‚¤ã‚«ãƒ¼'
          - 'ã‚³ãƒ¼ãƒ’ãƒ¼ã‚«ãƒƒãƒ—'
          - 'ã‚¹ãƒ—ãƒ¼ãƒ³'
          - 'ã©ã‚“ã¶ã‚Š'
      dishes4:
        required: false
        description: 'é£Ÿå™¨ 4'
        type: choice
        options:
          - ''
          - 'ãƒ—ãƒ­ãƒ†ã‚¤ãƒ³ã‚¹ãƒ—ãƒ¼ãƒ³'
          - 'ãƒ—ãƒ­ãƒ†ã‚¤ãƒ³ã‚·ã‚§ã‚¤ã‚«ãƒ¼'
          - 'ã‚³ãƒ¼ãƒ’ãƒ¼ã‚«ãƒƒãƒ—'
          - 'ã‚¹ãƒ—ãƒ¼ãƒ³'
          - 'ã©ã‚“ã¶ã‚Š'
      dishes5:
        required: false
        description: 'é£Ÿå™¨ 5'
        type: string
      dishes6:
        required: false
        description: 'é£Ÿå™¨ 6'
        type: string
      dishes7:
        required: false
        description: 'é£Ÿå™¨ 7'
        type: string
      minutes:
        required: false
        description: 'åˆ†'
        type: number
      seconds:
        required: false
        description: 'ç§’'
        type: number
      note:
        required: false
        description: 'ãƒ¡ãƒ¢'
        type: string

jobs:
  dishwashing:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "housework å®¶äº‹"
      template_name: "dishwashing"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
