name: 'cβ2: 🌿🥗 食事記録 / 食べたもの（選択式）'

on:
  workflow_dispatch:
    inputs:
      food:
        required: true
        description: '食べたもの'
        type: choice
        options:
          - ''
          - '☕️'
          - '甘い香りのモカブレンド'
          - 'コク深いリッチブレンド'
          - '💪'
          - 'バナナ'
          - 'プロテイン'
          - 'しっとりプレーン サラダチキン'
          - '爽やかバジル サラダチキン'
          - '生卵'
          - 'ゆで卵'
          - '🥜'
          - 'ミックスナッツ'
          - '🥗'
          - 'キャベツミックス'
          - '千切りキャベツのミックスサラダ'
          - '天使のキャベツを使った千切りキャベツ'
          - '冷凍ブロッコリー'
          - '🐟'
          - 'サーモン'
          - 'カツオ'
          - 'ブリ'
          - 'マグロ'
          - 'メバチマグロ'
          - 'さば水煮'
          - 'オイル不使用 シーチキン マイルド'
          - '納豆'
          - '豆腐'
          - '🍚'
          - '白米'
          - '玄米'
          - '焼き芋'
          - '🫐'
          - '冷凍ブルーベリー'
          - 'ネーブルオレンジ'
          - '紅ほっぺ'
          - 'ギリシャヨーグルト'
      category:
        required: true
        description: '分類'
        type: choice
        options:
          - ''
          - '☕️'
          - 'コーヒー'
          - '💪'
          - 'フルーツ'
          - 'プロテイン'
          - '鶏肉'
          - '鶏卵'
          - '🥜'
          - 'ナッツ'
          - '🥗'
          - '野菜'
          - '🐟'
          - '魚'
          - '豆'
          - '豆腐'
          - '🍚'
          - '白米'
          - '玄米'
          - 'さつまいも'
          - '🫐'
          - 'フルーツ'
          - 'ヨーグルト'
      quantity:
        required: true
        description: '分量'
        type: number
      unit:
        required: true
        description: '単位'
        type: choice
        options:
          - ''
          - '人前'
          - '個'
          - '本'
          - '杯'
          - '袋'
          - '箱'
          - 'g'
      impression:
        required: false
        description: '感想'
        type: string

jobs:
  food:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "food 食事記録"
      template_name: "food-eaten"
      template_repo: "noraworld/diary-templates"
      version: "0.2.3"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
