name: 'fÎ²5: ðŸ§¹ðŸ§¼ðŸ§´ è¡›ç”Ÿ'

on:
  workflow_dispatch:
    inputs:
      minutes:
        required: false
        description: 'åˆ†'
        type: number
      seconds:
        required: false
        description: 'ç§’'
        type: number
      note:
        required: false
        description: 'ãƒ¡ãƒ¢'
        type: string
      toys1:
        required: true
        description: 'ä½¿ç”¨å™¨å…· 1'
        type: choice
        options:
          - 'ã‚»ãƒ–ãƒ³ãƒ†ã‚£ãƒ¼ãƒ³'
          - ''
      toys2:
        required: false
        description: 'ä½¿ç”¨å™¨å…· 2'
        type: choice
        options:
          - ''
          - 'ã‚»ãƒ–ãƒ³ãƒ†ã‚£ãƒ¼ãƒ³'
      toys3:
        required: false
        description: 'ä½¿ç”¨å™¨å…· 3'
        type: choice
        options:
          - ''
          - 'ã‚»ãƒ–ãƒ³ãƒ†ã‚£ãƒ¼ãƒ³'
      toys4:
        required: false
        description: 'ä½¿ç”¨å™¨å…· 4'
        type: string
      toys5:
        required: false
        description: 'ä½¿ç”¨å™¨å…· 5'
        type: string
      toys6:
        required: false
        description: 'ä½¿ç”¨å™¨å…· 6'
        type: string
      toys7:
        required: false
        description: 'ä½¿ç”¨å™¨å…· 7'
        type: string

jobs:
  hygiene:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "housework å®¶äº‹"
      template_name: "hygiene"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
