name: 'fÎ²2: ğŸ§¹ğŸ§¼ğŸ‘• æ´—æ¿¯'

on:
  workflow_dispatch:
    inputs:
      minutes:
        required: false
        description: 'åˆ†'
        type: number
      seconds:
        required: false
        description: 'ç§’'
        type: number
      note:
        required: false
        description: 'ãƒ¡ãƒ¢'
        type: string
      clothes1:
        required: true
        description: 'è¡£é¡ 1'
        type: choice
        options:
          - ''
          - 'ä¸‹ç€'
          - 'é´ä¸‹'
          - 'ã‚·ãƒ£ãƒ„'
          - 'ä¸Šç€'
          - 'éƒ¨å±‹ç€ç”¨ã‚ºãƒœãƒ³'
          - 'å¤–å‡ºç”¨ã‚ºãƒœãƒ³'
          - 'æ‰‹æ‹­ãã‚¿ã‚ªãƒ«'
          - 'ãƒã‚¹ã‚¿ã‚ªãƒ«'
          - 'ã‚¢ã‚¤ãƒã‚¹ã‚¯'
          - 'ã¾ãã‚‰ã‚«ãƒãƒ¼'
          - 'ã‚·ãƒ¼ãƒ„'
      clothes2:
        required: false
        description: 'è¡£é¡ 2'
        type: choice
        options:
          - ''
          - 'ä¸‹ç€'
          - 'é´ä¸‹'
          - 'ã‚·ãƒ£ãƒ„'
          - 'ä¸Šç€'
          - 'éƒ¨å±‹ç€ç”¨ã‚ºãƒœãƒ³'
          - 'å¤–å‡ºç”¨ã‚ºãƒœãƒ³'
          - 'æ‰‹æ‹­ãã‚¿ã‚ªãƒ«'
          - 'ãƒã‚¹ã‚¿ã‚ªãƒ«'
          - 'ã‚¢ã‚¤ãƒã‚¹ã‚¯'
          - 'ã¾ãã‚‰ã‚«ãƒãƒ¼'
          - 'ã‚·ãƒ¼ãƒ„'
      clothes3:
        required: false
        description: 'è¡£é¡ 3'
        type: choice
        options:
          - ''
          - 'ä¸‹ç€'
          - 'é´ä¸‹'
          - 'ã‚·ãƒ£ãƒ„'
          - 'ä¸Šç€'
          - 'éƒ¨å±‹ç€ç”¨ã‚ºãƒœãƒ³'
          - 'å¤–å‡ºç”¨ã‚ºãƒœãƒ³'
          - 'æ‰‹æ‹­ãã‚¿ã‚ªãƒ«'
          - 'ãƒã‚¹ã‚¿ã‚ªãƒ«'
          - 'ã‚¢ã‚¤ãƒã‚¹ã‚¯'
          - 'ã¾ãã‚‰ã‚«ãƒãƒ¼'
          - 'ã‚·ãƒ¼ãƒ„'
      clothes4:
        required: false
        description: 'è¡£é¡ 4'
        type: choice
        options:
          - ''
          - 'ä¸‹ç€'
          - 'é´ä¸‹'
          - 'ã‚·ãƒ£ãƒ„'
          - 'ä¸Šç€'
          - 'éƒ¨å±‹ç€ç”¨ã‚ºãƒœãƒ³'
          - 'å¤–å‡ºç”¨ã‚ºãƒœãƒ³'
          - 'æ‰‹æ‹­ãã‚¿ã‚ªãƒ«'
          - 'ãƒã‚¹ã‚¿ã‚ªãƒ«'
          - 'ã‚¢ã‚¤ãƒã‚¹ã‚¯'
          - 'ã¾ãã‚‰ã‚«ãƒãƒ¼'
          - 'ã‚·ãƒ¼ãƒ„'
      clothes5:
        required: false
        description: 'è¡£é¡ 5'
        type: choice
        options:
          - ''
          - 'ä¸‹ç€'
          - 'é´ä¸‹'
          - 'ã‚·ãƒ£ãƒ„'
          - 'ä¸Šç€'
          - 'éƒ¨å±‹ç€ç”¨ã‚ºãƒœãƒ³'
          - 'å¤–å‡ºç”¨ã‚ºãƒœãƒ³'
          - 'æ‰‹æ‹­ãã‚¿ã‚ªãƒ«'
          - 'ãƒã‚¹ã‚¿ã‚ªãƒ«'
          - 'ã‚¢ã‚¤ãƒã‚¹ã‚¯'
          - 'ã¾ãã‚‰ã‚«ãƒãƒ¼'
          - 'ã‚·ãƒ¼ãƒ„'
      clothes6:
        required: false
        description: 'è¡£é¡ 6'
        type: choice
        options:
          - ''
          - 'ä¸‹ç€'
          - 'é´ä¸‹'
          - 'ã‚·ãƒ£ãƒ„'
          - 'ä¸Šç€'
          - 'éƒ¨å±‹ç€ç”¨ã‚ºãƒœãƒ³'
          - 'å¤–å‡ºç”¨ã‚ºãƒœãƒ³'
          - 'æ‰‹æ‹­ãã‚¿ã‚ªãƒ«'
          - 'ãƒã‚¹ã‚¿ã‚ªãƒ«'
          - 'ã‚¢ã‚¤ãƒã‚¹ã‚¯'
          - 'ã¾ãã‚‰ã‚«ãƒãƒ¼'
          - 'ã‚·ãƒ¼ãƒ„'
      clothes7:
        required: false
        description: 'è¡£é¡ 7'
        type: choice
        options:
          - ''
          - 'ä¸‹ç€'
          - 'é´ä¸‹'
          - 'ã‚·ãƒ£ãƒ„'
          - 'ä¸Šç€'
          - 'éƒ¨å±‹ç€ç”¨ã‚ºãƒœãƒ³'
          - 'å¤–å‡ºç”¨ã‚ºãƒœãƒ³'
          - 'æ‰‹æ‹­ãã‚¿ã‚ªãƒ«'
          - 'ãƒã‚¹ã‚¿ã‚ªãƒ«'
          - 'ã‚¢ã‚¤ãƒã‚¹ã‚¯'
          - 'ã¾ãã‚‰ã‚«ãƒãƒ¼'
          - 'ã‚·ãƒ¼ãƒ„'

jobs:
  laundry:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "housework å®¶äº‹"
      template_name: "laundry"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
