name: 'fÎ²4: ğŸ§¹ğŸ§¼ğŸ› ï¸ ãƒ¡ãƒ³ãƒ†ãƒŠãƒ³ã‚¹'

on:
  workflow_dispatch:
    inputs:
      minutes:
        required: false
        description: 'åˆ†'
        type: number
      seconds:
        required: false
        description: 'ç§’'
        type: number
      note:
        required: false
        description: 'ãƒ¡ãƒ¢'
        type: string
      supplies1:
        required: true
        description: 'æ¶ˆè€—å“ 1'
        type: choice
        options:
          - ''
          - 'ã‚´ãƒŸè¢‹äº¤æ›'
          - 'ãƒãƒ³ãƒ‰ã‚½ãƒ¼ãƒ—è©°æ›¿'
          - 'ã‚·ãƒ£ãƒ³ãƒ—ãƒ¼è©°æ›¿'
          - 'ãƒœãƒ‡ã‚£ã‚½ãƒ¼ãƒ—è©°æ›¿'
          - 'ã‚·ãƒ¼ãƒªãƒ³ã‚°ãƒ©ã‚¤ãƒˆãƒªãƒ¢ã‚³ãƒ³é›»æ± äº¤æ›'
          - 'ã‚¨ã‚¢ã‚³ãƒ³ãƒªãƒ¢ã‚³ãƒ³é›»æ± äº¤æ›'
          - 'å¸æ°—å£ãƒ•ã‚£ãƒ«ã‚¿ãƒ¼äº¤æ›'
      supplies2:
        required: false
        description: 'æ¶ˆè€—å“ 2'
        type: choice
        options:
          - ''
          - 'ã‚´ãƒŸè¢‹äº¤æ›'
          - 'ãƒãƒ³ãƒ‰ã‚½ãƒ¼ãƒ—è©°æ›¿'
          - 'ã‚·ãƒ£ãƒ³ãƒ—ãƒ¼è©°æ›¿'
          - 'ãƒœãƒ‡ã‚£ã‚½ãƒ¼ãƒ—è©°æ›¿'
          - 'ã‚·ãƒ¼ãƒªãƒ³ã‚°ãƒ©ã‚¤ãƒˆãƒªãƒ¢ã‚³ãƒ³é›»æ± äº¤æ›'
          - 'ã‚¨ã‚¢ã‚³ãƒ³ãƒªãƒ¢ã‚³ãƒ³é›»æ± äº¤æ›'
          - 'å¸æ°—å£ãƒ•ã‚£ãƒ«ã‚¿ãƒ¼äº¤æ›'
      supplies3:
        required: false
        description: 'æ¶ˆè€—å“ 3'
        type: choice
        options:
          - ''
          - 'ã‚´ãƒŸè¢‹äº¤æ›'
          - 'ãƒãƒ³ãƒ‰ã‚½ãƒ¼ãƒ—è©°æ›¿'
          - 'ã‚·ãƒ£ãƒ³ãƒ—ãƒ¼è©°æ›¿'
          - 'ãƒœãƒ‡ã‚£ã‚½ãƒ¼ãƒ—è©°æ›¿'
          - 'ã‚·ãƒ¼ãƒªãƒ³ã‚°ãƒ©ã‚¤ãƒˆãƒªãƒ¢ã‚³ãƒ³é›»æ± äº¤æ›'
          - 'ã‚¨ã‚¢ã‚³ãƒ³ãƒªãƒ¢ã‚³ãƒ³é›»æ± äº¤æ›'
          - 'å¸æ°—å£ãƒ•ã‚£ãƒ«ã‚¿ãƒ¼äº¤æ›'
      supplies4:
        required: false
        description: 'æ¶ˆè€—å“ 4'
        type: choice
        options:
          - ''
          - 'ã‚´ãƒŸè¢‹äº¤æ›'
          - 'ãƒãƒ³ãƒ‰ã‚½ãƒ¼ãƒ—è©°æ›¿'
          - 'ã‚·ãƒ£ãƒ³ãƒ—ãƒ¼è©°æ›¿'
          - 'ãƒœãƒ‡ã‚£ã‚½ãƒ¼ãƒ—è©°æ›¿'
          - 'ã‚·ãƒ¼ãƒªãƒ³ã‚°ãƒ©ã‚¤ãƒˆãƒªãƒ¢ã‚³ãƒ³é›»æ± äº¤æ›'
          - 'ã‚¨ã‚¢ã‚³ãƒ³ãƒªãƒ¢ã‚³ãƒ³é›»æ± äº¤æ›'
          - 'å¸æ°—å£ãƒ•ã‚£ãƒ«ã‚¿ãƒ¼äº¤æ›'
      supplies5:
        required: false
        description: 'æ¶ˆè€—å“ 5'
        type: string
      supplies6:
        required: false
        description: 'æ¶ˆè€—å“ 6'
        type: string
      supplies7:
        required: false
        description: 'æ¶ˆè€—å“ 7'
        type: string

jobs:
  maintenance:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "housework å®¶äº‹"
      template_name: "maintenance"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
