name: 'aÎ³Ğ°: ğŸš€ğŸªœ ãƒ¯ãƒ³ã‚¹ãƒ†ãƒƒãƒ—ãƒãƒ£ãƒ¬ãƒ³ã‚¸' # https://chatgpt.com/share/6942cb5d-f1d4-8004-961a-41cbb77301ce

on:
  workflow_dispatch:
    inputs:
      engagement:
        required: true
        description: 'ä»Šæ—¥ã¯ã€è‡ªåˆ†ã®ã‚„ã‚ŠãŸã„ã“ã¨ã«ä¸€æ­©è§¦ã‚ŒãŸï¼Ÿ'
        type: boolean
      activity:
        required: true
        description: 'ä»Šæ—¥ã€è§¦ã‚ŒãŸã“ã¨ï¼ˆã‚¿ã‚¹ã‚¯ã‚ã‚Œã°ãƒªãƒ³ã‚¯ä»˜ãï¼‰'
        type: string
      mode:
        required: true
        description: 'ä»Šæ—¥ã¯ã€ã©ã†é€²ã‚ãŸï¼Ÿ'
        type: choice
        options:
          - ''
          - 'æ™‚é–“'
          - 'ã‚´ãƒ¼ãƒ«'
          - 'æ™‚é–“ & ã‚´ãƒ¼ãƒ«'
      # duration / milestone åˆä½“ç‰ˆ
      # å…¥åŠ›ã®ã¨ãã«ä¸€ã¤ã§æ¸ˆã‚€ã®ã§æ¥½ã ãŒè¨˜éŒ²ã®ç²¾åº¦ãŒè½ã¡ã‚‹
      #
      # extent:
      #   required: true
      #   description: 'ä»Šæ—¥ã€ã©ã‚Œãã‚‰ã„è§¦ã‚ŒãŸï¼Ÿ'
      #   type: choice
      #   options:
      #     - ''
      #     - '5'
      #     - '10'
      #     - '20'
      #     - '40'
      #     - '60'
      #     - 'è§¦ã‚ŒãŸ'
      #     - 'ä¸€åŒºåˆ‡ã‚Š'
      #     - 'ã²ã¨ã¤çµ‚ãˆãŸ'
      sessions:
        required: false
        description: 'ã‚»ãƒƒã‚·ãƒ§ãƒ³ã®é•·ã•ï¼ˆåˆ†ï¼‰'
        type: choice
        options:
          - '20'
          - '' # é•·ã•ã‚’è¨ˆæ¸¬ã—ã¦ã„ãªã„å ´åˆã¯ãƒ‡ãƒ•ã‚©ãƒ«ãƒˆã‚’å¤–ã™ãŸã‚
          - '5'
          - '10'
          - '15'
          - '25'
          - '30'
        default: '20'
      duration:
        required: false
        description: 'ä»Šæ—¥ã¯ã€ä½•ã‚»ãƒƒã‚·ãƒ§ãƒ³è§¦ã‚ŒãŸï¼Ÿ'
        type: number # 'choice' ã«ã™ã‚‹ã¨ 2.25 ã¨ã‹å…¥ã‚Œã¥ã‚‰ã„ï¼ˆã€Œå…¨ç«¯æ•°ç”¨æ„ã™ã‚‹ã‚“ã‹ï¼Ÿã€ã£ã¦ãªã‚‹ï¼‰
      milestone:
        required: false
        description: 'ä»Šæ—¥ã¯ã€ã©ã“ã¾ã§é€²ã‚“ã ï¼Ÿ'
        type: choice
        options:
          - ''
          - 'è§¦ã‚ŒãŸ'
          - 'ä¸€åŒºåˆ‡ã‚Š'
          - 'ã²ã¨ã¤çµ‚ãˆãŸ'
      note:
        required: false
        description: 'ä»Šæ—¥ã®ã²ã¨ã“ã¨'
        type: string
      #
      # æŒ¯ã‚Šè¿”ã‚Š / æ”¹å–„ç‚¹ / åçœ / ç›®æ¨™ / è©•ä¾¡ / ãƒ¢ãƒãƒ™ãƒ¼ã‚·ãƒ§ãƒ³ ãªã©ã¯å…¥ã‚Œãªã„ã“ã¨ï¼ˆé‡è¦ï¼‰
      #   https://chatgpt.com/share/6942cb5d-f1d4-8004-961a-41cbb77301ce
      #
      motto:
        required: false
        description: 'è§¦ã‚ŒãŸã‚‰ OKï¼ ãã‚Œã ã‘ã§ 100 ç‚¹ ğŸŒ¸'
        type: choice
        options:
          - ''

jobs:
  progress:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "progress ãƒ¯ãƒ³ã‚¹ãƒ†ãƒƒãƒ—ãƒãƒ£ãƒ¬ãƒ³ã‚¸"
      template_name: "progress"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
