name: 'cÎ±Ğ²: ğŸŒ¿ğŸ’¤ ç¡çœ è¨˜éŒ² / å°±å¯ãƒ»èµ·åºŠæ™‚åˆ»'

on:
  workflow_dispatch:
    inputs:
      night1:
        required: true
        description: 'å°±å¯æ™‚åˆ» 1'
        type: string
      morning1:
        required: true
        description: 'èµ·åºŠæ™‚åˆ» 1'
        type: string
      night2:
        required: false
        description: 'å°±å¯æ™‚åˆ» 2'
        type: string
      morning2:
        required: false
        description: 'èµ·åºŠæ™‚åˆ» 2'
        type: string
      impression:
        required: false
        description: 'æ‰€æ„Ÿ'
        type: string
      merged:
        required: true
        description: 'å‰æ—¥åˆ†ã¨ã®ãƒãƒ¼ã‚¸æœ‰ç„¡'
        type: boolean
        default: false

jobs:
  sleep:
    uses: noraworld/diary-templates-assistant/.github/workflows/base.yml@main
    with:
      search_query: "sleep ç¡çœ è¨˜éŒ²"
      template_name: "sleep-bedtime"
      template_repo: "noraworld/diary-templates"
      version: "0.1.0"
    secrets:
      token: ${{ secrets.GH_TOKEN }}
